#!/bin/bash

echo "mode: count" > postal.coverprofile
cat *.cover.out | grep -v mode: | sort -r | awk '{if($1 != last) {print $0;last=$1}}' >> postal.coverprofile
rm *.cover.out
gocov convert postal.coverprofile | gocov-html > dist/coverage.html
