#!/bin/bash

set -e

PLATFORM=$(echo $1 | cut -d_ -f2 | cut -d- -f1)
ARCH=$(echo $1 | cut -d_ -f2 | cut -d- -f2)

# Build binaries
gox "-os=${PLATFORM}" "-arch=${ARCH}" \
    -output="dist/postalctl_{{.OS}}-{{.Arch}}" github.com/jive/postal
