#!/bin/bash

chmod +x dist/postalctl_linux-amd64

cat <<DF > dist/Dockerfile
FROM alpine
ADD postalctl_linux-amd64 /postalctl
EXPOSE 7542
ENTRYPOINT ["/postalctl"]
DF

docker build -t jive/postal:${1} dist
